name: Notify Discord

on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed]
  watch:
  fork:
  repository_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification with URL Preview
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          EVENT_NAME="${{ github.event_name }}"
          ACTION="${{ github.event.action }}"
          REPO="${{ github.repository }}"
          ACTOR="${{ github.actor }}"

          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_URL="${{ github.event.issue.html_url }}"
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          REPO_URL="https://github.com/${REPO}"

          MESSAGE="New GitHub Event in $REPO by $ACTOR"

          if [[ "$EVENT_NAME" == "issues" ]]; then
            if [[ "$ACTION" == "opened" ]]; then
              MESSAGE="New Issue Created: $ISSUE_TITLE by $ACTOR\n$ISSUE_URL"
            elif [[ "$ACTION" == "closed" ]]; then
              MESSAGE="Issue Closed: $ISSUE_TITLE by $ACTOR\n$ISSUE_URL"
            fi
          elif [[ "$EVENT_NAME" == "pull_request" ]]; then
            if [[ "$ACTION" == "opened" ]]; then
              MESSAGE="New Pull Request: $PR_TITLE by $ACTOR\n$PR_URL"
            elif [[ "$ACTION" == "closed" ]]; then
              MESSAGE="Pull Request Closed: $PR_TITLE by $ACTOR\n$PR_URL"
            fi
          elif [[ "$EVENT_NAME" == "watch" ]]; then
            MESSAGE="⭐ Repo Starred by $ACTOR\n$REPO_URL"
          elif [[ "$EVENT_NAME" == "fork" ]]; then
            MESSAGE="Repo Forked by $ACTOR\n$REPO_URL"
          else
            MESSAGE="$REPO_URL"
          fi

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"$MESSAGE\"}" \
               $DISCORD_WEBHOOK
